spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thanhthai3010/microservices-spring/
          search-paths:
            - "ms-config-properties/{application}/{profile}"