spring:
  kafka:
    consumer:
      group-id: ms_mail_consumer
    bootstrap-servers: localhost:9092
    topic:
      userCreated: USER_CREATED_TOPIC
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
security:
  basic:
    enabled: false
